### ISSUE TITLE
Tutorial status?

### ISSUE THREAD

**Issue by Nezteb** [harabat/django-htmx#1]
From the README:

> Warning
> 
> I'm rewriting this tutorial in depth, to improve the structure, the explanations, the code, and implement the "Coming soon" sections.
> 
> The rewrite is expected to be finished in July/August.

I was just wondering if this tutorial was still being worked on. If not, no worries!

I ask because I think it'd be super neat to have this listed on the official examples page! https://htmx.org/server-examples/

**Comment by harabat** [comment]
Thanks! Seems like people are using this tutorial, so status is now `Active`! I'll add it to htmx.org when I've added that section.
